"use strict";
var MilkaApple;
(function (MilkaApple) {
    let seitenaufbau = document.getElementById("seitenaufbau");
    let dasmachtmilkaaus = document.createElement("div");
    dasmachtmilkaaus.id = "dasmachtmilkaaus";
    let dasmachtmilkaausdiv = document.createElement("div");
    dasmachtmilkaausdiv.id = "dasmachtmilkaausdiv";
    let pgeschmack = document.createElement("p");
    pgeschmack.classList.add("parani");
    let pzutaten = document.createElement("p");
    pzutaten.classList.add("parani");
    let palpenmilch = document.createElement("p");
    palpenmilch.classList.add("parani");
    let phochtaelern = document.createElement("p");
    phochtaelern.classList.add("parani");
    let pauszutaten = document.createElement("p");
    pauszutaten.classList.add("parani");
    let prezeptur = document.createElement("p");
    prezeptur.classList.add("parani");
    let pdrinist = document.createElement("p");
    pdrinist.classList.add("parani");
    let pmilka = document.createElement("p");
    pmilka.classList.add("parani");
    pgeschmack.innerHTML = "Unverwechselbar zarter Geschmack.";
    pzutaten.innerHTML = "Hochwertige Zutaten.";
    palpenmilch.innerHTML = "100% Alpenmilch aus Tälern und";
    phochtaelern.innerHTML = "Hochtälern der Alpen.";
    pauszutaten.innerHTML = "Ausgewählte Zutaten in jeder Tafel Schokolade.";
    prezeptur.innerHTML = "Einheitliche Rezeptur.";
    pdrinist.innerHTML = "Drin ist, was draufsteht.";
    pmilka.innerHTML = "Das ist Milka.";
    dasmachtmilkaausdiv.appendChild(pgeschmack);
    dasmachtmilkaausdiv.appendChild(pzutaten);
    dasmachtmilkaausdiv.appendChild(palpenmilch);
    dasmachtmilkaausdiv.appendChild(phochtaelern);
    dasmachtmilkaausdiv.appendChild(phochtaelern);
    dasmachtmilkaausdiv.appendChild(pauszutaten);
    dasmachtmilkaausdiv.appendChild(pdrinist);
    dasmachtmilkaausdiv.appendChild(pmilka);
    dasmachtmilkaaus.appendChild(dasmachtmilkaausdiv);
    seitenaufbau.appendChild(dasmachtmilkaaus);
    let genaudierichtigegroeße = document.createElement("div");
    genaudierichtigegroeße.id = "genaudierichtigegroeße";
})(MilkaApple || (MilkaApple = {}));
//# sourceMappingURL=script.js.map